# Generated by Django 5.0.4 on 2024-05-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasta',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
