# Generated by Django 5.0.4 on 2024-06-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0003_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
