# Generated by Django 5.0.4 on 2024-06-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0004_alter_signature_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='fasta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgw_api.fasta'),
        ),
    ]
