# Generated by Django 5.0.4 on 2024-06-04 14:33

import django.core.validators
import django.db.models.deletion
import mgw_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0005_alter_signature_fasta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasta',
            name='file',
            field=models.FileField(upload_to=mgw_api.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['fa', 'fasta', 'fsa', 'fna', 'FASTA']), mgw_api.models.validate_fasta_content]),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_setting', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
