# Generated by Django 5.0.4 on 2024-06-04 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0006_alter_fasta_file_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
