# Generated by Django 5.0.4 on 2024-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0008_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='SRA_database',
            field=models.BooleanField(default=True, help_text='SRA database'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='kmer_21',
            field=models.BooleanField(default=True, help_text='21 k-mer'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='kmer_31',
            field=models.BooleanField(default=False, help_text='31 k-mer'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='kmer_51',
            field=models.BooleanField(default=False, help_text='51 k-mer'),
        ),
    ]
