# Generated by Django 5.0.4 on 2024-06-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0011_signature_submitted_alter_result_settings_used'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
