# Generated by Django 5.0.6 on 2024-07-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0014_alter_result_settings_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='settings_used',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
