# Generated by Django 5.0.6 on 2024-07-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0018_rename_created_at_result_created_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.JSONField()),
                ('sort_column', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='asc', max_length=4)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgw_api.result')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
