# Generated by Django 5.0.6 on 2024-07-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0019_filtersetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersetting',
            name='filters',
            field=models.JSONField(default=dict),
        ),
    ]
