# Generated by Django 5.0.6 on 2024-07-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0020_alter_filtersetting_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtersetting',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='filtersetting',
            name='range_filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='filtersetting',
            name='sort_reverse',
            field=models.BooleanField(default=False),
        ),
    ]
