# Generated by Django 5.0.6 on 2024-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0021_remove_filtersetting_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fasta',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
