# Generated by Django 5.0.6 on 2024-08-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0025_signature_result_pk_signature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
