# Generated by Django 5.1 on 2025-01-14 11:39

import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0028_rename_created_date_result_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='database',
            field=models.JSONField(default=functools.partial(list, *(['SRA'],), **{}), help_text='List of databases'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='kmer',
            field=models.JSONField(default=functools.partial(list, *([21],), **{}), help_text='List of k-mers'),
        ),
    ]
