# Generated by Django 5.1 on 2025-02-24 14:25

import django.core.validators
import mgw_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgw_api', '0030_alter_result_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasta',
            name='file',
            field=models.FileField(upload_to=mgw_api.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['fa', 'fasta', 'fsa', 'fna', 'gz']), mgw_api.models.validate_fasta_content]),
        ),
    ]
