version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-security:
        applies-to: security-updates
        patterns:
          - "*"
      all-versions:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-versions:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-versions:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "docker-compose"
    directory: "/example-config"
    schedule:
      interval: "weekly"
    groups:
      all-versions:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: "conda"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-versions:
        applies-to: version-updates
        patterns:
          - "*"
