repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5120']
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
        types_or: [python, markdown, shell]
      - id: trailing-whitespace
        types_or: [python, markdown, shell]
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
