services:

  mgwatch-django:
    image: mgwatch:local
    container_name: mgwatch-django
    restart: unless-stopped
    volumes:
      - ${DATA_DIR}/mgw-data:/code/mgw-data
      - ${DATA_DIR}/mgw-db:/code/db
    depends_on:
      mgwatch-mongodb:
        condition: service_started
    entrypoint: /bin/sh -c
    command: [ "conda run --no-capture-output -n mgw gunicorn --workers 2 --threads 2 --bind 0.0.0.0:9080 mgw.wsgi:application" ]

  mgwatch-mongodb:
    image: mongo:6.0.18
    container_name: mgwatch-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example1
    volumes:
      - ${DATA_DIR}/mongodb:/data/db

  mgwatch-proxy:
    image: $DOCKER_NGINX_IMAGE
    container_name: mgwatch-proxy
    volumes:
      - ./conf/nginx/templates:/etc/nginx/templates
      # Not sure how we need to set this up
      - ./static:/static
      - ./media:/media
    environment:
      - NGINX_PORT=8000
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - mgwatch-django
