# This compose file is meant to be used *with* the compose.yml file, and only
# adds/overrides some settings. Mainly we expose a few ports that might be
# useful for debugging, and mount the current dir under /code in the backend
# container so that you can make live changes to the code without needing to
# rebuild the container.
services:
  mgwatch:
    environment:
      - DEBUG=True
      - LOG_LEVEL=DEBUG
    ports: !override
      - "8100:8100"
    command: ["pixi run --frozen ./manage.py runserver 0.0.0.0:8100"]
    #    build: .
    #    develop:
    #      watch:
    #        - action: sync
    #          path: ./mgw
    #          target: /code/mgw
    #          initial_sync: true
    #        - action: sync
    #          path: ./mgw_api
    #          target: /code/mgw_api
    #          initial_sync: true
    #        - action: sync
    #          path: ./templates
    #          target: /code/templates
    #          initial_sync: true
    #        - action: sync
    #          path: ./mgw
    #          target: /code/mgw
    #          initial_sync: true
    #        - action: rebuild
    #          path: pixi.toml
  mgwatch-mongodb:
    ports: !override
      - "27018:27017"
  mgwatch-postgres:
    ports: !override
      - "5433:5432"
  mgwatch-redis:
    ports: !override
      - "6379:6379"
  mgwatch-celery-interactive:
    environment:
      - DEBUG=True
      - LOG_LEVEL=DEBUG
  mgwatch-celery-maintenance:
    environment:
      - DEBUG=True
      - LOG_LEVEL=DEBUG
  mgwatch-celery-beat:
    environment:
      - DEBUG=True
      - LOG_LEVEL=DEBUG
