"""
Django settings for mgw project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import logging
import os
from datetime import datetime
from datetime import timedelta
from pathlib import Path
from urllib.parse import unquote
from urllib.parse import urlsplit

import environ
import ldap
from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured
from django_auth_ldap.config import LDAPSearch

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, False),
    SECRET_KEY=str,
    ALLOWED_HOSTS=(str, ""),
    MGW_URL=(str, None),
    CSRF_TRUSTED_ORIGINS=(str, ""),
    TIME_ZONE=(str, "Europe/Berlin"),
    DATA_DIR=(Path, BASE_DIR / ".." / "mgw-data"),
    DB_DIR=(Path, "/data-db"),
    MONGO_URI=(str, None),
    EMAIL_HOST=(str, None),
    EMAIL_PORT=(int, 1025),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_HOST_USER=(str, None),
    EMAIL_HOST_PASSWORD=(str, None),
    DEFAULT_FROM_EMAIL=(str, "test@mail.de"),
    LOG_DIR=(Path, Path("/logs")),
    LOG_LEVEL=(str, "INFO"),
    INDEX_FROM_SCRATCH=(bool, False),
    INDEX_MAX_SIGNATURES=(int, 100000),
    DELETE_INDEXED_SIGS=(bool, False),
    START_DATE=(str, "2024-03-15"),
    END_DATE=(str, "2024-03-15"),
    LIB_SOURCE=(list, []),
    WORT_ATTEMPTS=(int, 1),
    WORT_SKIP_FAILED=(bool, True),
    MAX_DOWNLOADS=(int, 100),
    INDEX_MIN_ITERATOR=(int, 38),
    LDAP_SERVER_URI=(str, None),
    LDAP_BIND_DN=(str, None),
    LDAP_BIND_PASSWORD=(str, None),
    LDAP_SEARCH_ROOT=(str, None),
    LDAP_ATTR_USERNAME=(str, None),
    LDAP_ATTR_EMAIL=(str, None),
    MAX_SEARCH_RESULTS=(int, 100),
    REDIS_URL=(str, "redis://mgwatch-redis:6379/0"),
    CELERY_TASK_ALWAYS_EAGER=(bool, False),
    CELERY_TASK_EAGER_PROPAGATES=(bool, True),
    CELERY_TASK_RESULT_TIMEOUT=(int, 60 * 60 * 6),
    CELERY_LOCK_TIMEOUT=(int, 60 * 60 * 6),
    CELERY_LOCK_BLOCKING_TIMEOUT=(int, 60),
    SECURE_SSL_REDIRECT=(bool, False),
    SECURE_PROXY_SSL_HEADER_ENABLED=(bool, False),
    SESSION_COOKIE_SECURE=(bool, False),
    CSRF_COOKIE_SECURE=(bool, False),
    SECURE_HSTS_SECONDS=(int, 0),
    SECURE_HSTS_INCLUDE_SUBDOMAINS=(bool, False),
    SECURE_HSTS_PRELOAD=(bool, False),
    SECURE_CONTENT_TYPE_NOSNIFF=(bool, True),
    SECURE_REFERRER_POLICY=(str, "same-origin"),
    DATA_UPLOAD_MAX_MEMORY_SIZE=(int, 10 * 1024 * 1024),
    FILE_UPLOAD_MAX_MEMORY_SIZE=(int, 10 * 1024 * 1024),
    MAX_FASTA_UPLOAD_SIZE=(int, 50 * 1024 * 1024),
    AXES_ENABLED=(bool, True),
    AXES_FAILURE_LIMIT=(int, 5),
    AXES_COOLOFF_MINUTES=(int, 30),
    AXES_RESET_ON_SUCCESS=(bool, True),
    AXES_IPWARE_PROXY_COUNT=(int, 0),
    RETENTION_CLEANUP_ENABLED=(bool, True),
    RETENTION_UNWATCHED_RESULTS_DAYS=(int, 180),
    RETENTION_WATCHED_RESULTS_DAYS=(int, 365),
    RETENTION_SIGNATURES_DAYS=(int, 180),
    RETENTION_UNPROCESSED_FASTA_DAYS=(int, 7),
    RETENTION_COMPLETED_JOBS_DAYS=(int, 180),
    RETENTION_FAILED_JOBS_DAYS=(int, 90),
    RETENTION_TEMP_FILES_DAYS=(int, 7),
    RETENTION_FAILED_INDEX_FILES_DAYS=(int, 30),
    RETENTION_LOG_FILES_DAYS=(int, 180),
)

environ.Env.read_env(BASE_DIR / "vars.env")

UNSAFE_SECRET_MARKERS = (
    "CHANGE_ME",
    "django-insecure-",
)
UNSAFE_SECRET_VALUES = {
    "",
    "dummy",
    "example",
    "example1",
    "password",
    "secret",
    "test",
    "test-secret",
    "CHANGE_ME_LONG_RANDOM_DJANGO_SECRET_KEY",
    "CHANGE_ME_LONG_RANDOM_MONGODB_PASSWORD",
    "django-insecure-em&y0o^!@ha-kujz4qch11-a*qy8t3peg8@%+=(_+-bnwzr2%z",
}


def _is_unsafe_secret(value):
    if value is None:
        return True
    normalized_value = str(value).strip().strip("\"'")
    if normalized_value in UNSAFE_SECRET_VALUES:
        return True
    return any(marker in normalized_value for marker in UNSAFE_SECRET_MARKERS)


def _mongo_password_from_uri(uri):
    if not uri:
        return None
    try:
        return unquote(urlsplit(uri).password or "")
    except ValueError:
        return None


def unsafe_production_secret_reasons(secret_key, mongo_uri):
    reasons = []
    if _is_unsafe_secret(secret_key):
        reasons.append("SECRET_KEY is unset or uses a known placeholder/default value")

    mongo_password = _mongo_password_from_uri(mongo_uri)
    if _is_unsafe_secret(mongo_password):
        reasons.append(
            "MONGO_URI is unset or uses a known placeholder/default password"
        )
    return reasons


# The hostname to use for links (e.g. https://mgwatch.example.com)
MGW_URL = env("MGW_URL")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# The maximum number of search results to provide
MAX_SEARCH_RESULTS = env("MAX_SEARCH_RESULTS")
DATA_UPLOAD_MAX_MEMORY_SIZE = env("DATA_UPLOAD_MAX_MEMORY_SIZE")
FILE_UPLOAD_MAX_MEMORY_SIZE = env("FILE_UPLOAD_MAX_MEMORY_SIZE")
MAX_FASTA_UPLOAD_SIZE = env("MAX_FASTA_UPLOAD_SIZE")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# MongoDB used for SRA metadata
MONGO_URI = env("MONGO_URI")

# Wort updates
INDEX_FROM_SCRATCH = env("INDEX_FROM_SCRATCH")
# number of signatures in each index
INDEX_MAX_SIGNATURES = env("INDEX_MAX_SIGNATURES")
DELETE_INDEXED_SIGS = env("DELETE_INDEXED_SIGS")
INDEX_MIN_ITERATOR = env("INDEX_MIN_ITERATOR")
# format: "yyyy-mm-dd" if START_DATE set to "auto", start and end will be set to today - 2 days; current index is on "2023-09-27"
START_DATE = env("START_DATE")
END_DATE = env("END_DATE")
# will be ignored if list is empty; possible lib_source values: ["GENOMIC", "GENOMIC SINGLE CELL", "METAGENOMIC", "METATRANSCRIPTOMIC", "OTHER", "SYNTHETIC", "TRANSCRIPTOMIC", "TRANSCRIPTOMIC SINGLE CELL", "VIRAL RNA"]
LIB_SOURCE = env("LIB_SOURCE")
WORT_ATTEMPTS = env("WORT_ATTEMPTS")
# skip failed wort attempts
WORT_SKIP_FAILED = env("WORT_SKIP_FAILED")
# limit total of IDS trying to download, set to 0 if no limit
MAX_DOWNLOADS = env("MAX_DOWNLOADS")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

if not DEBUG:
    unsafe_secret_reasons = unsafe_production_secret_reasons(SECRET_KEY, MONGO_URI)
    if unsafe_secret_reasons:
        raise ImproperlyConfigured(
            "Unsafe production secrets are configured: "
            + "; ".join(unsafe_secret_reasons)
        )

ALLOWED_HOSTS = [] if env("ALLOWED_HOSTS") == "" else env("ALLOWED_HOSTS").split(",")
CSRF_TRUSTED_ORIGINS = (
    [] if env("CSRF_TRUSTED_ORIGINS") == "" else env("CSRF_TRUSTED_ORIGINS").split(",")
)

SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if env.bool("SECURE_PROXY_SSL_HEADER_ENABLED", default=not DEBUG)
    else None
)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_HSTS_SECONDS = env.int(
    "SECURE_HSTS_SECONDS", default=31536000 if not DEBUG else 0
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=not DEBUG
)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)
SECURE_CONTENT_TYPE_NOSNIFF = env.bool("SECURE_CONTENT_TYPE_NOSNIFF", default=True)
SECURE_REFERRER_POLICY = env("SECURE_REFERRER_POLICY", default="same-origin")

STATIC_ROOT = BASE_DIR / "static"

# Logging
LOGGER = logging.getLogger(__name__)

LOG_DIR = env("LOG_DIR")
if not LOG_DIR.is_dir():
    LOG_DIR.mkdir(parents=True, exist_ok=True)
LOG_LEVEL = env("LOG_LEVEL")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"},
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
        "app_log_file": {
            "level": LOG_LEVEL,
            "class": "logging.FileHandler",
            "filename": os.path.join(
                LOG_DIR, f'{datetime.today().strftime("%Y_%m_%d")}.log'
            ),
            "formatter": "simple",
        },
    },
    "loggers": {
        "": {
            "level": LOG_LEVEL,
            "handlers": ["console", "app_log_file"],
        },
    },
}

# Application definition

#    'branchwater.apps.BranchwaterConfig',
INSTALLED_APPS = [
    "mgw_api.apps.MgwApiConfig",
    "axes",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mgw.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mgw.wsgi.application"

DATA_DIR = env("DATA_DIR")

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DB_DIR = Path(env("DB_DIR"))
DB_DIR.mkdir(parents=True, exist_ok=True)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DB_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = env("TIME_ZONE")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = DATA_DIR / "media"
MEDIA_URL = "/media/"

REDIS_URL = env("REDIS_URL")

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_TASK_ALWAYS_EAGER = env("CELERY_TASK_ALWAYS_EAGER")
CELERY_TASK_EAGER_PROPAGATES = env("CELERY_TASK_EAGER_PROPAGATES")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = env("CELERY_TASK_RESULT_TIMEOUT")
CELERY_TASK_SOFT_TIME_LIMIT = max(1, CELERY_TASK_TIME_LIMIT - 60)
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_ACKS_ON_FAILURE_OR_TIMEOUT = True
CELERY_TASK_REJECT_ON_WORKER_LOST = False
CELERY_TASK_DEFAULT_QUEUE = "maintenance"
CELERY_TASK_DEFAULT_PRIORITY = 5
CELERY_TASK_ROUTES = {
    "mgw_api.tasks.run_signature_pipeline": {"queue": "interactive"},
    "mgw_api.tasks.run_search_task": {"queue": "interactive"},
    "mgw_api.tasks.run_create_signature_task": {"queue": "interactive"},
    "mgw_api.tasks.run_metadata_task": {"queue": "maintenance"},
    "mgw_api.tasks.run_downloads_task": {"queue": "maintenance"},
    "mgw_api.tasks.run_index_task": {"queue": "indexing"},
    "mgw_api.tasks.run_watch_task": {"queue": "watches"},
    "mgw_api.tasks.run_daily_pipeline_task": {"queue": "maintenance"},
    "mgw_api.tasks.run_retention_cleanup_task": {"queue": "maintenance"},
}
CELERY_BEAT_SCHEDULE = {
    "daily-maintenance-pipeline": {
        "task": "mgw_api.tasks.run_daily_pipeline_task",
        "schedule": crontab(minute=0, hour=1),
        "options": {"queue": "maintenance"},
    },
    "daily-retention-cleanup": {
        "task": "mgw_api.tasks.run_retention_cleanup_task",
        "schedule": crontab(minute=30, hour=2),
        "options": {"queue": "maintenance"},
    },
}
CELERY_TASK_RESULT_TIMEOUT = env("CELERY_TASK_RESULT_TIMEOUT")
CELERY_LOCK_TIMEOUT = env("CELERY_LOCK_TIMEOUT")
CELERY_LOCK_BLOCKING_TIMEOUT = env("CELERY_LOCK_BLOCKING_TIMEOUT")

RETENTION_CLEANUP_ENABLED = env("RETENTION_CLEANUP_ENABLED")
RETENTION_UNWATCHED_RESULTS_DAYS = env("RETENTION_UNWATCHED_RESULTS_DAYS")
RETENTION_WATCHED_RESULTS_DAYS = env("RETENTION_WATCHED_RESULTS_DAYS")
RETENTION_SIGNATURES_DAYS = env("RETENTION_SIGNATURES_DAYS")
RETENTION_UNPROCESSED_FASTA_DAYS = env("RETENTION_UNPROCESSED_FASTA_DAYS")
RETENTION_COMPLETED_JOBS_DAYS = env("RETENTION_COMPLETED_JOBS_DAYS")
RETENTION_FAILED_JOBS_DAYS = env("RETENTION_FAILED_JOBS_DAYS")
RETENTION_TEMP_FILES_DAYS = env("RETENTION_TEMP_FILES_DAYS")
RETENTION_FAILED_INDEX_FILES_DAYS = env("RETENTION_FAILED_INDEX_FILES_DAYS")
RETENTION_LOG_FILES_DAYS = env("RETENTION_LOG_FILES_DAYS")

if CELERY_TASK_ALWAYS_EAGER:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "mgwatch-local-cache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }

if DEBUG:
    MIDDLEWARE += ("debug_toolbar.middleware.DebugToolbarMiddleware",)
    INSTALLED_APPS += ("debug_toolbar",)
    INTERNAL_IPS = ("127.0.0.1",)
    DEBUG_TOOLBAR_CONFIG = {
        "INTERCEPT_REDIRECTS": False,
    }

AXES_ENABLED = env("AXES_ENABLED")
AXES_FAILURE_LIMIT = env("AXES_FAILURE_LIMIT")
AXES_COOLOFF_TIME = timedelta(minutes=env("AXES_COOLOFF_MINUTES"))
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]
AXES_RESET_ON_SUCCESS = env("AXES_RESET_ON_SUCCESS")
AXES_HTTP_RESPONSE_CODE = 429
AXES_IPWARE_PROXY_COUNT = env("AXES_IPWARE_PROXY_COUNT") or None
if AXES_IPWARE_PROXY_COUNT:
    AXES_IPWARE_META_PRECEDENCE_ORDER = (
        "HTTP_X_FORWARDED_FOR",
        "REMOTE_ADDR",
    )
else:
    AXES_IPWARE_META_PRECEDENCE_ORDER = ("REMOTE_ADDR",)
MIDDLEWARE += ("axes.middleware.AxesMiddleware",)

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"
LOGIN_URL = "/login/"

################################################################################
EMAIL_HOST = env("EMAIL_HOST")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_PORT = env("EMAIL_PORT")
    EMAIL_USE_TLS = env("EMAIL_USE_TLS")
    EMAIL_HOST_USER = env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
else:
    # If an SMTP server isn't specified, write emails to the console
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

################################################################################
# By default use Django's default user authentication
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Optionally check LDAP/Active Directory server for user accounts first
if env("LDAP_SERVER_URI"):
    AUTH_LDAP_CONNECTION_OPTIONS = {ldap.OPT_REFERRALS: 0}
    AUTH_LDAP_SERVER_URI = env("LDAP_SERVER_URI")
    AUTH_LDAP_BIND_DN = env("LDAP_BIND_DN")
    AUTH_LDAP_BIND_PASSWORD = env("LDAP_BIND_PASSWORD")

    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        env("LDAP_SEARCH_ROOT"), ldap.SCOPE_SUBTREE, "(cn=%(user)s)"
    )
    AUTH_LDAP_USER_ATTR_MAP = {
        "username": env("LDAP_ATTR_USERNAME"),
        "email": env("LDAP_ATTR_EMAIL"),
    }
    # Populate Django's user database automatically with data from LDAP
    AUTH_LDAP_ALWAYS_UPDATE_USER = True
    # Try LDAP first, before reverting to default user authentication
    AUTHENTICATION_BACKENDS.insert(1, "django_auth_ldap.backend.LDAPBackend")
